---
- name: Install required packages
  yum:
    name:
      - python3-psycopg2
    state: latest

- name: Import the PostgreSQL GPG key
  rpm_key:
    state: present
    key: "{{ postgresql_rpm_key }}"

- name: Install PostgreSQL
  ansible.builtin.yum:
    name: "{{ postgresql_packages }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"

- name: Initialize PostgreSQL database
  ansible.builtin.command:
    cmd: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/{{ postgresql_version }}/data/PG_VERSION

- name: Ensure PostgreSQL is enabled and started
  ansible.builtin.service:
    name: "postgresql"
    enabled: yes
    state: started
    
- name: Ensure PostgreSQL is listening on *
  lineinfile:
    dest: /var/lib/pgsql/data/postgresql.conf
    regexp: '^#listen_addresses\s*='
    line: "listen_addresses = '*'"
    state: present
  notify: Restart Postgresql

- name: Add new configuration to "pg_hba.conf"
  blockinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    block: |
      host    all             all             0.0.0.0/0                md5
      host    all             all             ::/0                     md5
  notify: Restart Postgresql

- name: Change peer identification to trust
  ansible.builtin.shell: /bin/sed -i 's/ident/trust/' /var/lib/pgsql/data/pg_hba.conf
  notify: Restart Postgresql

- name: Create a Superuser PostgreSQL database user
  become: true
  become_user: postgres
  postgresql_user:
    name: 'postgres'
    password: "{{ lookup('password', '/root/04-postgres_admin_password chars=ascii_letters,digits,hexdigits length=15') }}"
    role_attr_flags: CREATEDB,SUPERUSER,CREATEROLE
    encrypted: yes
    state: present

- name: Insert postgres superuser name into user password file
  blockinfile:
    dest: /root/04-postgres_admin_password
    insertbefore: BOF
    block: |
      Админ-пользователь postgres:
      Логин: postgres

- name: Create app database
  postgresql_db:
    state: present
    name: "{{ short_vhost }}"
  become: true
  become_user: postgres

- name: Create db user
  postgresql_user:
    state: present
    name: "{{ short_vhost }}"
    password: "{{ lookup('password', '/root/03-postgres_password chars=ascii_letters,digits,hexdigits length=15') }}"
  become: true
  become_user: postgres

- name: Insert postgres user name into user password file
  blockinfile:
    dest: /root/03-postgres_password
    insertbefore: BOF
    block: |
      Данные для доступа к базе данных:
      Имя БД: {{ short_vhost }}
      Пользователь: {{ short_vhost }}

- name: Grant db user access to app db
  postgresql_privs:
    type: database
    database: "{{ short_vhost }}"
    roles: "{{ short_vhost }}"
    grant_option: no
    privs: all
  become: true
  become_user: postgres

- name: Allow md5 connection for the db user
  postgresql_pg_hba:
    dest: "/var/lib/pgsql/data/pg_hba.conf"
    contype: host
    databases: all
    method: md5
    users: "{{ short_vhost }}"
    create: true
  become: true
  become_user: postgres
  notify: Restart Postgresql
  tags: md5
