---
- name: Install nginx
  yum:
    name: nginx
    state: latest
  notify: restart nginx

- name: Change nginx.conf file
  copy: dest=/etc/nginx/nginx.conf src=nginx_centos.conf owner=root group=root
  notify: restart nginx

- name: Add nginx conf.d configs
  copy: dest=/etc/nginx/conf.d/{{ item }}.conf src=conf.d/{{ item }}.conf owner=root group=root
  loop:
    - 00-conn
    - 01-gzip
    - 02-proxy
    - 03-timeout
    - 04-ssl
    - 05-open_file
  notify: restart nginx

# disabled because task takes too long
#- name: generate dhparam file in background
#  shell: "(nice -n 19 openssl dhparam -out /etc/nginx/dhparam.pem 4096 2>&1 &)"
#  async: 3600
#  poll: 0
#  register: dhparam_sleeper

- name: Create /etc/nginx/vhosts/
  file: state=directory path=/etc/nginx/vhosts/ mode=0755

- name: Add nginx vhosts configs
  template:
    src: "{{ item.file }}"
    dest: "{{ item.target }}"
    mode: 0644
  loop:
    - { file: 'vhost_centos.conf.j2', target: '/etc/nginx/vhosts/{{ vhost }}.conf' }
    - { file: 'ipvhost.conf.j2', target: '/etc/nginx/vhosts/{{ ansible_default_ipv4.address }}.conf' }
  notify: restart nginx

- name: Fix httproxy vulnerability
  blockinfile:
    marker: "## {mark} httpoxy vulnerability fix"
    block: |
      fastcgi_param  HTTP_PROXY         "";
    insertafter: EOF
    path: /etc/nginx/fastcgi_params

- name: Enable http(s) on firewall-cmd
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
    zone: public
  loop:
    - http
    - https
