---
- hosts: vps
  tasks:
    - name: Add repos and update package manager cache before main playbook execution
      import_tasks: base_os_setup.yml
      #this is useful to save time on playbook execution

- hosts: vps
  roles:
    - nginx
    - apache2
    - nginx_bundle
    - mysql
    - phpmyadmin
    - sftp
    - fail2ban
    - wordpress
    - certbot
