- name: restart php-fpm centos
  service:
    name: php{{ php_version }}-php-fpm
    state: restarted

- name: restart php-fpm debian
  service:
    name: php{{ php_version_u }}-fpm
    state: restarted

- name: restart apache
  service:
    name: httpd
    state: restarted
  when: apache2_status.stat.exists
  
- name: restart nginx
  service:
    name: nginx
    state: restarted
  when: nginx_status.stat.exists

- name: restart httpd
  service:
    name: httpd
    state: restarted
  when: httpd_status.stat.exists
