---

- name: Clear dir /var/www/
  shell: rm -rf /var/www/*

- name: Setup the Git repo
  git: repo=https://github.com/scotch-io/node-todo.git dest=/var/www/{{ vhost }} accept_hostkey=yes

- name: Add node.js user
  user:
    name: node
    home: /var/www/{{ vhost }}
    shell: /bin/bash
    password: "{{ lookup('password', '/tmp/pagsnagt chars=ascii_letters,digits,hexdigits length=15') }}"

- name: Ensure that the application file permissions are set properly
  file: path=/var/www/{{ vhost }}
        recurse=yes
        owner=node
        group=node
        state=directory

- name: Ensure dependencies are present.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo.changed

- name: Ensure Node.js and npm are installed.
  apt:
    name: "nodejs"
    state: present

- name: Install PM2
  npm:
    name: pm2
    global: yes

- name: Install angular
  npm:
    name: "@angular/cli"
    global: yes

- name: Install Express
  npm:
    name: express
    global: yes

- name: Install npm package from package.json.
  npm:
    path: /var/www/{{ vhost }}
