---
- name: Gather service facts
  service_facts:

- name: Set frontend fact to nginx if nginx service is running
  set_fact:
    frontend: "nginx"
  when: "'nginx.service' in ansible_facts.services and ansible_facts.services['nginx.service'].state == 'running'"

- name: Set frontend fact to httpd if httpd service is running and nginx is not
  set_fact:
    frontend: "httpd"
  when: "'httpd.service' in ansible_facts.services and ansible_facts.services['httpd.service'].state == 'running' and (frontend is not defined or frontend != 'nginx')"

- name: Set backend fact to httpd if both nginx and httpd services are running
  set_fact:
    backend: "httpd"
  when: "'nginx.service' in ansible_facts.services and 'httpd.service' in ansible_facts.services and ansible_facts.services['nginx.service'].state == 'running' and (frontend is defined and frontend == 'nginx')"

- name: install python-passlib for centos7
  yum:
    name: python-passlib
    state: latest
  when: ansible_facts['distribution_major_version'] not in ["8", "9"]

- name: install python3-passlib for centos8
  yum:
    name: python3-passlib
    state: latest
  when: ansible_facts['distribution_major_version'] in ["8", "9"]

- name: Extract phpMyAdmin
  unarchive:
    src: "https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/phpMyAdmin-{{ phpmyadmin_version }}-all-languages.tar.gz"
    dest: "/usr/share/"
    remote_src: yes

- name: Install PMA
  shell: |
    mv /usr/share/phpMyAdmin-{{ phpmyadmin_version }}-all-languages /usr/share/phpmyadmin
    cp /usr/share/phpmyadmin/config.sample.inc.php /usr/share/phpmyadmin/config.inc.php

- name: generate pma secret
  lineinfile:
    path: /usr/share/phpmyadmin/config.inc.php
    line: "$cfg['blowfish_secret'] = '{{ lookup('password', 'chars=ascii_letters,digits,hexdigits,punctuation length=32') }}';"
    regexp: '.*blowfish_secret.*'

- name: add mysqli extension line into config
  lineinfile:
    path: /usr/share/phpmyadmin/config.inc.php
    line: "$cfg['Servers'][$i]['extension'] = 'mysqli';"
    insertafter: '.*auth_type.*'

- name: create pma temp dir
  file:
    state: directory
    path: /usr/share/phpmyadmin/tmp/
    group: apache
    mode: 0770

- name: copy phpmyadmin nginx conf block
  blockinfile:
    marker: ''
    insertbefore: '^\t## pma'
    block: |
      rewrite ^/pma/?(.*)$ /phpmyadmin/$1 redirect;

      location /phpmyadmin/setup {
          deny all;
      }

      location /phpmyadmin/ {
        auth_basic "Speak, friend, and enter.";
        auth_basic_user_file conf.d/htpasswd;

        root /usr/share;
        fastcgi_index index.php;
        fastcgi_pass unix:/var/run/phpmyadmin.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|bmp|rtf|js|swf|flv|avi|djvu|mp3)$ {
          expires max;
        }
      }

    path: /etc/nginx/vhosts/{{ ansible_default_ipv4.address }}.conf
  notify: restart nginx
  when: frontend == "nginx" and backend is not defined

- name: copy modphp nginx handler config
  blockinfile:
    marker: ''
    insertbefore: '^\t## pma'
    block: |
      rewrite ^/pma/?(.*)$ /phpmyadmin/$1 redirect;

      location /phpmyadmin/setup {
        deny all;
      }

      location /phpmyadmin/ {
        root /usr/share;

        auth_basic "Speak, friend, and enter.";
        auth_basic_user_file conf.d/htpasswd;

        proxy_pass http://127.0.0.1:8080;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 300;
        client_max_body_size 256m;

        proxy_buffer_size 16k;
        proxy_buffers 32 16k;

        location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|bmp|rtf|js|swf|flv|avi|djvu|mp3)$ {
          expires max;
        }
      }

    path: /etc/nginx/vhosts/{{ ansible_default_ipv4.address }}.conf
  when: frontend == "nginx" and backend == "httpd"
  notify: restart nginx
  
- name: copy httpd vhost config frontend nginx
  template:
    src: pma_centos_apache.conf.j2
    dest: /etc/httpd/conf.d/{{ ansible_default_ipv4.address }}.conf
  when: frontend == "nginx" and backend == "httpd"
  notify: restart httpd

- name: copy httpd vhost config frontend apache
  template:
    src: pma_centos_apache_lamp.conf.j2
    dest: /etc/httpd/conf.d/{{ ansible_default_ipv4.address }}.conf
  when: frontend == "httpd"
  notify: restart httpd

- name: Ensure the default Apache site port is 8080
  lineinfile:
    path: /etc/httpd/conf.d/{{ vhost }}.conf
    regexp: '^<VirtualHost'
    line: '<VirtualHost 127.0.0.1:8080>'
  notify: restart httpd
  when: frontend == "nginx" and backend == "httpd"

- name: add http auth for pma
  htpasswd:
    path: /etc/nginx/conf.d/htpasswd
    name: pma_admin
    password: "{{ lookup('password', '/root/02-pma_password chars=ascii_letters,digits,hexdigits length=15') }}"
  notify: restart nginx
  when: frontend == "nginx"

- name: add http auth for pma
  htpasswd:
    path: /etc/httpd/.htpasswd
    name: pma_admin
    password: "{{ lookup('password', '/root/02-pma_password chars=ascii_letters,digits,hexdigits length=15') }}"
  notify: restart httpd
  when: frontend == "httpd"

- name: insert pmd_admin user name into password file
  blockinfile:
    dest: /root/02-pma_password
    insertbefore: BOF
    block: |

      Веб-интерфейс для работы с базой данных:
      http://{{ ansible_default_ipv4.address }}/pma/
      Данные для http авторизации:
      Логин: pma_admin
