---
nodejs_version: "20.x"

npm_config_prefix: "/usr/local/lib/npm"

npm_config_unsafe_perm: "false"

nodejs_generate_etc_profile: "true"

nodejs_npm_global_packages:
- name: "pm2"
- name: "express"
- name: "@angular/cli"
nodejs_package_json_path: "/var/www/{{ vhost }}/"
