---
- name: Add MariaDB {{ mariadb_version }}  repo
  yum_repository:
    name: MariaDB
    description: MariaDB {{ mariadb_version }} {{ ansible_distribution }} {{ ansible_distribution_major_version }}
    baseurl: https://mirror.mariadb.org/yum/{{ mariadb_version }}/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}-amd64
    gpgkey: https://mirror.mariadb.org/yum/RPM-GPG-KEY-MariaDB

- name: Fix module_hotfixes Mariadb repo
  lineinfile:
    path: /etc/yum.repos.d/MariaDB.repo
    insertafter: 'name ='
    regexp: '^module_hotfixes'
    line: 'module_hotfixes = 1'
  when: ansible_facts['distribution_major_version'] in ["8", "9"]

- name: Install MariaDB and dependencies
  block:
    - name: Install MariaDB for RHEL/Derivatives 7
      yum:
        name: "{{ mariadb_packages_7 }}"
      when: ansible_facts['distribution_major_version'] not in ["8", "9"]
    - name: Install dependencies for RHEL/Derivatives 8 and 9
      dnf:
        name: "{{ mariadb_packages_8_9 }}"
      when: ansible_facts['distribution_major_version'] in ["8", "9"]
    - name: Install MariaDB-server for RHEL/Derivatives 8 and 9
      dnf:
        name: MariaDB-server
        disablerepo: AppStream
      when: ansible_facts['distribution_major_version'] in ["8", "9"]

- name: Install mariadb-server for RHEL/Derivatives 8
  dnf:
    name: MariaDB-server
    disablerepo: AppStream
  when: ansible_facts['distribution_major_version'] in ["8", "9"]

- name: Configure MariaDB
  block:
    - name: Change mariadb bind-address
      lineinfile:
        path: /etc/my.cnf.d/server.cnf
        regexp: '^#bind-address'
        line: 'bind-address = 127.0.0.1'
    - name: Add log-error
      blockinfile:
        path: /etc/my.cnf.d/server.cnf
        insertafter: '[mysqld]'
        block: |
          log-error = {{ mariadb_log_file }}
    - name: Ensure mariadb is started and enabled
      service:
        name: mariadb
        state: started
        enabled: yes

- name: Setup MariaDB Users and Databases
  block:
    - name: Change root password
      mysql_user:
        state: present
        name: root
        host: localhost
        login_unix_socket: /var/lib/mysql/mysql.sock
        password: "{{ lookup('password', '/root/04-mysqlr_password chars=ascii_letters,digits,hexdigits length=15') }}"

    - name: Copy root mysql password file
      copy:
        dest: /root/.my.cnf
        src: root_my_cnf
        owner: root
        group: root
        mode: 0660

    - name: Add root password to root homedir my.cnf file
      replace:
        path: /root/.my.cnf
        regexp: '^password'
        replace: 'password="{{ file_contents }}"'
      vars:
        file_contents: "{{ lookup('file', '/root/04-mysqlr_password') }}"

    - name: Add website db
      mysql_db:
        state: present
        name: "{{ short_vhost }}"
        collation: utf8_unicode_ci
      tags: website_stack

    - name: Add db user
      mysql_user:
        state: present
        name: "{{ short_vhost }}"
        host: localhost
        password: "{{ lookup('password', '/root/03-mysql_password chars=ascii_letters,digits,hexdigits length=15') }}"
        priv: '{{ short_vhost }}.*:ALL'
      tags: website_stack

    - name: Set dbuser password
      set_fact:
        dbuser_password: "{{ lookup('file', '/root/03-mysql_password') }}"

    - name: Insert mysql user name into user password file
      blockinfile:
        dest: /root/03-mysql_password
        insertbefore: BOF
        block: |
          Данные для доступа к базе данных:
          Имя БД: {{ short_vhost }}
          Пользователь: {{ short_vhost }}
      tags: website_stack

    - name: Create pfxadmin db
      mysql_db:
        name: postfixadmin
        collation: utf8_unicode_ci
      tags: mailserver

    - name: Create pfxadmin mysql user
      mysql_user:
        name: postfixadmin
        password: "{{ lookup('password', '/root/060-pfxadmin_db_password chars=ascii_letters,digits length=20') }}"
        priv: 'postfixadmin.*:ALL'
        host: localhost
      tags: mailserver

    - name: Remove anonymous users
      mysql_user:
        state: absent
        name: ''
        host_all: yes

    - name: Remove test db
      mysql_db:
        state: absent
        name: test

    - name: Insert root mysql user name into root password file
      blockinfile:
        dest: /root/04-mysqlr_password
        insertbefore: BOF
        block: |
          Пароль от mysql root-пользователя:

#TODO
# 1. add log-error=/var/log/mariadb/mariadb.log to [mysqld]
# 2. add other main parameters
