---
- name: install proftpd and trivia
    apt:
      name: proftpd
    state: latest
    update_cache: yes
    cache_valid_time: 42300

- name: check if proftpd is started and enabled
  service:
    name: proftpd
    state: started
    enabled: yes

- name: enable ftp on ufw
  ufw:
    rule: allow
    port: ftp
    proto: tcp

- name: create site group
  group:
    name: {{ short_vhost }}

- name: create site user
  user:
    name: {{ short_vhost }}
    group: {{ short_vhost }}
    password: {{ short_vhost }}
    shell: /bin/bash

- name: change ftp server name
  lineinfile:
    path: /etc/proftpd/proftpd.conf
    regexp: '^ServerName'
    line: 'ServerName        FTP_{{ short_vhost }}'
  notify: restart proftpd

- name: change chroot to vhost dir
  lineinfile:
    path: /etc/proftpd/proftpd.conf
    regexp: '^# DefaultRoot'
    line: 'DefaultRoot    /var/www/{{ vhost }}    {{ short_vhost }}'
  notify: restart proftpd

- name: change chroot to vhost dir
  lineinfile:
    path: /etc/proftpd/proftpd.conf
    regexp: '^# RequireValidShell'
    line: 'RequireValidShell        off'
  notify: restart proftpd

# TODO
# Generate secure password for user
# randopass mkpasswd --method=sha-512
