---

- name: add php handler block for nginx
  blockinfile:
    marker: ' '
    path: /etc/nginx/vhosts/{{ vhost }}.conf
    insertafter: '## handler ##'
    block: |
      location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #httpoxy vulnerability fix
        proxy_set_header Proxy "";

        proxy_read_timeout 300;
        client_max_body_size 256m;

        proxy_buffer_size 16k;
        proxy_buffers 32 16k;
      }
  notify: restart nginx

- name: Ensure the default Apache port is 8080
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen 8080

